# Generated by Django 5.2.8 on 2026-03-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '2. Product'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': '3. Product Image'},
        ),
    ]
