# Generated by Django 6.0.3 on 2026-04-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0004_remove_product_image_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
    ]
