# Generated by Django 6.0.3 on 2026-04-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0005_productimage_unique_primary_image_per_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['primary'], name='idx_primary_flag'),
        ),
    ]
