# Generated by Django 6.0.3 on 2026-04-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0006_productimage_idx_primary_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
